### ISSUE TITLE
Invisibility Vial?

### ISSUE THREAD

**Issue by Blue-Shadow** [Kyle873/DoomRPG#25] opened 2015-03-22 06:39 UTC
See the edit in this [post](http://forum.zdoom.org/viewtopic.php?p=821726#p821726).

**Comment by Kyle873** [comment] 2015-03-27 09:42
Since I have absolutely no way to reproduce this or even a hint at where to even begin looking, I'm going to close this unless something like it happens again.

**Closed by Kyle873** 2015-03-27 09:42 UTC

**Comment by Blue-Shadow** [comment] 2015-03-27 10:50
See [this line](https://github.com/Kyle873/DoomRPG/blob/master/DoomRPG/scripts/ItemData.ds#L155) in `ItemData.ds`

**Comment by Kyle873** [comment] 2015-03-27 11:21
Well, I'm a colossal idiot. Fixed.
